name: Build de image Docker

on:
  pull_request:
    branches:
     - development

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image Docker
        run: |
          cd desafio-02/nginx/
          docker build -t nginx-custom:1.0 .

        #empacotar image Docker
      - name: Export Docker image as .tar
        run: |
          docker save nginx-custom:1.0 -o /tmp/nginx-custom.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nginx-custom
          path: /tmp/nginx-custom.tar
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nginx-custom
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/nginx-custom.tar

      - name: Teste de conexão
        run: |
          docker run -dit --name nginx -p 8070:80 nginx-custom:1.0
          sleep 5
          curl -lv http://localhost:8070
    