name: Test self-hosted AWS EC2

on:
  push:
    branches:
      - master
jobs:
  test-runner:
    runs-on: [self-hosted, linux]
    steps:
      - name: Testar conexão
        run: echo "Self-hosted runner está funcionando!"
